name: 'Build Linux Kernel Package For Archlinux'
description: 'Test build an AUR package in Docker container'
branding:
  icon: user-check
  color: gray-dark
runs:
  using: 'docker'
  image: 'Dockerfile'
